### ISSUE TITLE
Serial connection loop crash

### ISSUE THREAD

**Issue by piedtyper** [OctoPrint/OctoPrint#207]
2013-07-26 23:20:12,528 - octoprint.util.comm - ERROR - Something crashed inside the serial connection loop, please report this in OctoPrint's bug tracker:
Traceback (most recent call last):
  File "/home/pi/OctoPrint/octoprint/util/comm.py", line 825, in _monitor
    self._handleResendRequest(line)
  File "/home/pi/OctoPrint/octoprint/util/comm.py", line 842, in _handleResendRequest
    lineToResend = int(line.split()[1])
ValueError: invalid literal for int() with base 10: 'stopped'

**Comment by iLeonelPerea** [comment]
I have the sae problem.. but the serial.log is empty..

**Comment by markwal** [comment]
@iLeonelPerea, serial.log is turned off by default because it grows too quickly.  You have to turn it on in Settings->Serial Connection.  It's the checkbox with the "warning" box next to it.
