### ISSUE TITLE
When restarting Klipper service, ocotoprint reports error, refuses to reconnect

### ISSUE THREAD

**Issue by DanielJoyce** [OctoPrint/OctoPrint#3563]
Restarting clipper while octoprint is running, Octoprint ( not the klipper plugin ) reports an error in comm.py and clicking reconnect continues to fail

#### What did you expect to happen?

Octoprint should be able to reconnect

#### What happened instead?

Octoprint refuses to reconnect, 

#### Version of OctoPrint

1.4.0

#### Operating System running OctoPrint

ubuntu 20.04 on rpi 4, 64 bit

#### Printer model & used firmware incl. version

klipper 0.8, ender5

#### Link to octoprint.log

It appears comm.py dies:
```
2020-05-09 12:15:21,376 - octoprint.util.comm - ERROR - Unexpected error while reading from serial port
Traceback (most recent call last):
  File "/opt/octoprint/lib/python2.7/site-packages/octoprint/util/comm.py", line 2823, in _readline
    ret = self._serial.readline()
  File "/opt/octoprint/lib/python2.7/site-packages/octoprint/util/comm.py", line 4968, in readline
    c = self.read(1)
  File "/opt/octoprint/lib/python2.7/site-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

Trying to reconnect by any means fails

Expect patch incoming.

I have read the FAQ.

**Comment by DanielJoyce** [comment]
Scratch that, octoprint-klipper plugin is screwing up the config. If the connection dies, it refuses to use specified virtual serial port and defaults to tmp-printer. Ugh.
