### ISSUE TITLE
AttributeError: 'LoginManager' object has no attribute 'reload_user'

### ISSUE THREAD

**Issue by bzed** [OctoPrint/OctoPrint#3600]
Downloading timelapses results in this exception:

```
2020-06-11 22:08:49,879 - tornado.application - ERROR - Uncaught exception GET /downloads/timelapse/circle_20200611141803-fail.mpg (10.125.0.1)
Traceback (most recent call last):
  File "/home/bzed/tools/OctoPrint/venv/lib/python3.7/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/bzed/tools/OctoPrint/src/octoprint/server/util/tornado.py", line 1006, in get
    self._access_validation(self.request)
  File "/home/bzed/tools/OctoPrint/src/octoprint/server/util/tornado.py", line 1305, in f
    validator(request)
  File "/home/bzed/tools/OctoPrint/src/octoprint/server/util/tornado.py", line 1285, in f
    app.login_manager.reload_user()
AttributeError: 'LoginManager' object has no attribute 'reload_user'
```

Fallout of the upgrade of flask-login.

https://github.com/maxcountryman/flask-login/pull/378 says

- Rename LoginManager.reload_user to LoginManager._update_request_context_with_user

I've tried to replace it, but then I get a 403 error instead of the 500 from the exception.
The function was not only renamed, but enhanced with an extra line of code:
```ctx.user = self.anonymous_user() if user is None else user```

**Comment by foosel** [comment]
Fixed by the above commit. I wish more people would adhere to semver and reflect breaking changes in their changelogs, but alas, it is what it is. Thanks for reporting and analysing!
