### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info  while installing "octoprint-tuyasmartplug"

### ISSUE THREAD

**Issue by definitely-not-a-t-rex** [OctoPrint/OctoPrint#3622]
I'm not sure whether I should ask here or on ziirish's github but while trying to install his plugin I get: 
```
Installing plugin "OctoPrint-TuyaSmartplug" from https://github.com/ziirish/OctoPrint-TuyaSmartplug/archive/master.zip...
/home/pi/OctoPrint/venv/bin/python2 -m pip --disable-pip-version-check install https://github.com/ziirish/OctoPrint-TuyaSmartplug/archive/master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/ziirish/OctoPrint-TuyaSmartplug/archive/master.zip
Downloading https://github.com/ziirish/OctoPrint-TuyaSmartplug/archive/master.zip
Requirement already satisfied: OctoPrint in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint-TuyaSmartplug==0.2.3) (1.4.0)
Collecting pyaes==1.6.1
Downloading pyaes-1.6.1.tar.gz (28 kB)
Collecting pytuya==7.0.6
Downloading pytuya-7.0.6.zip (11 kB)
ERROR: Command errored out with exit status 1:
command: /home/pi/OctoPrint/venv/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3GpkLM/pytuya/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3GpkLM/pytuya/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3GpkLM/pytuya/pip-egg-info
cwd: /tmp/pip-install-3GpkLM/pytuya/
Complete output (7 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-3GpkLM/pytuya/setup.py", line 9, in <module>
from pytuya.const import __author__, __version__
File "pytuya/__init__.py", line 28, in <module>
import pyaes  # https://github.com/ricmoo/pyaes
ImportError: No module named pyaes
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output
```
The problem seem to be with pyaes, has anybody who got the issue managed to fix it or am I better off just using a relay connected to the printer rather than a smartplug?

**Comment by foosel** [comment]
That's an issue with the plugin's dependencies, not OctoPrint. So best ask the plugin author.
