### ISSUE TITLE
ImportError: No module named pigpio

### ISSUE THREAD

**Issue by DjSteker** [OctoPrint/OctoPrint#3666]
**I found this:**

```
 File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_GSLC/__init__.py", line 4, in <module>
    import pigpio
ImportError: No module named pigpio

```

**Is it as easy as adding the GPIO library in the folder?**

**Comment by foosel** [comment]
That's a problem with a third party plugin you installed, not OctoPrint. Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)

**Comment by fieldOfView** [comment]
The tracker for the plugin in question can be found here: https://github.com/Skiepp/GCodeSuperLaserController

**Comment by DjSteker** [comment]
okay
thank you :)
Do I delete the message? because the problem is several plugins

**Comment by fieldOfView** [comment]
The issue is "closed", and that suffices.

If the problem occurs in several plugins, it will have to be fixed in each plugin individually. If one of those plugins comes bundled with OctoPrint (not OctoPi!), please let us know here.

**Comment by DjSteker** [comment]
This is what comes out of my console (the program works well and I can use it and even plugins except the photo plugin per layer).     _and just that plugin wantedmake a modification "that takes the photo without interrupting anything"_

```
pi@raspberrypi:~ $ ~/OctoPrint/venv/bin/octoprint serve
2020-07-31 02:16:35,110 - octoprint.startup - INFO - ******************************************************************************
2020-07-31 02:16:35,113 - octoprint.startup - INFO - Starting OctoPrint 1.4.0
2020-07-31 02:16:35,113 - octoprint.startup - INFO - ******************************************************************************
2020-07-31 02:16:35,911 - octoprint.startup - INFO - We don't appear to be online, not fetching plugin blacklist
2020-07-31 02:16:35,996 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2020-07-31 02:16:37,843 - octoprint.plugin.core - ERROR - Error loading plugin GSLC
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 967, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 71, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_GSLC/__init__.py", line 4, in <module>
    import pigpio
ImportError: No module named pigpio
2020-07-31 02:16:38,069 - octoprint.plugins.octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2020-07-31 02:16:38,095 - octoprint.plugin.core - INFO - Found 24 plugin(s) providing 24 mixin implementations, 41 hook handlers
2020-07-31 02:16:38,237 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2020-07-31 02:16:38,378 - octoprint.server - INFO - Intermediary server started
2020-07-31 02:16:38,380 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2020-07-31 02:16:38,541 - octoprint.plugin.core - ERROR - Error loading plugin GSLC
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 967, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 71, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_GSLC/__init__.py", line 4, in <module>
    import pigpio
ImportError: No module named pigpio
2020-07-31 02:16:38,548 - octoprint.plugin.core - INFO - Found 24 plugin(s) providing 24 mixin implementations, 41 hook handlers
2020-07-31 02:16:38,584 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2020-07-31 02:16:39,018 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2020-07-31 02:16:39,024 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: u"Need(method='role', value=u'plugin_action_command_prompt_interact')")
2020-07-31 02:16:39,025 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: u"Need(method='role', value=u'plugin_announcements_read')")
2020-07-31 02:16:39,026 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: u"Need(method='role', value=u'plugin_announcements_manage'), Need(method='role', value=u'plugin_announcements_read')")
2020-07-31 02:16:39,027 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: u"Need(method='role', value=u'plugin_appkeys_admin')")
2020-07-31 02:16:39,029 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: u"Need(method='role', value=u'plugin_backup_access')")
2020-07-31 02:16:39,030 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: u"Need(method='role', value=u'plugin_logging_manage')")
2020-07-31 02:16:39,031 - octoprint.server - INFO - Added new permission from plugin pi_support: PLUGIN_PI_SUPPORT_STATUS (needs: u"Need(method='role', value=u'plugin_pi_support_check')")
2020-07-31 02:16:39,032 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: u"Need(method='role', value=u'plugin_pluginmanager_manage')")
2020-07-31 02:16:39,034 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: u"Need(method='role', value=u'plugin_pluginmanager_install'), Need(method='role', value=u'plugin_pluginmanager_manage')")
2020-07-31 02:16:39,036 - octoprint.server - INFO - Added new permission from plugin printer_safety_check: PLUGIN_PRINTER_SAFETY_CHECK_DISPLAY (needs: u"Need(method='role', value=u'plugin_printer_safety_check_display')")
2020-07-31 02:16:39,038 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: u"Need(method='role', value=u'plugin_softwareupdate_check')")
2020-07-31 02:16:39,040 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: u"Need(method='role', value=u'plugin_softwareupdate_update')")
2020-07-31 02:16:40,170 - octoprint.util.pip - INFO - Using "/home/pi/OctoPrint/venv/bin/python2 -m pip" as command to invoke pip
2020-07-31 02:16:41,047 - octoprint.util.pip - INFO - Version of pip is 20.1.1
2020-07-31 02:16:41,048 - octoprint.util.pip - INFO - pip installs to /home/pi/OctoPrint/venv/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-07-31 02:16:41,049 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-07-31 02:16:41,210 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2020-07-31 02:16:41,227 - octoprint.plugin.core - INFO - Initialized 24 plugin implementation(s)
2020-07-31 02:16:41,241 - octoprint.plugins.actioncommands - INFO - Add command definition 'action:Ventilador hotend' = M106 S200 P1
2020-07-31 02:16:41,247 - octoprint.plugin.core - INFO - 24 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Action Commands (0.2) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_actioncommands
|  Action Trigger (0.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_actiontrigger
|  Announcement Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/backup
|  Change Filament Plugin (0.3.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_Change_Filament
|  Core Wizard (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  Detailed Progress (0.2.5) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_detailedprogress
|  Discovery (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/discovery
|  DryRun Plugin (1.2.0) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_DryRun
|  Error Tracking (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/errortracking
|  Firmware Updater (1.7.0) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_firmwareupdater
|  Fullscreen Plugin (0.0.5) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_fullscreen
|  Gcodebar Plugin (0.1.5) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_GCodeBar
|  Logging (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/logging
|  Login UI (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/loginui
|  M300 Player (0.1.1) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_M300Player
|  Pi Support Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2020-07-31 02:16:41,264 - octoprint.environment - INFO - Detected environment is Python 2.7.16 under Linux (linux2). Details:
|  hardware:
|      cores: 4
|      freq: 1400.0
|      ram: 971038720
|  os:
|      id: linux
|      platform: linux2
|  plugins:
|      pi_support:
|          model: Raspberry Pi 3 Model B Plus Rev 1.3
|  python:
|      pip: 20.1.1
|      version: 2.7.16
|      virtualenv: /home/pi/OctoPrint/venv
2020-07-31 02:16:41,285 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2020-07-31 02:16:41,320 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2020-07-31 02:16:42,389 - octoprint.server - INFO - Shutting down intermediary server...
2020-07-31 02:16:42,457 - octoprint.server - INFO - Intermediary server shut down
2020-07-31 02:16:42,461 - octoprint.events - INFO - Processing startup event, this is our first event
2020-07-31 02:16:42,462 - octoprint.events - INFO - Adding 0 events to queue that were held back before startup event
2020-07-31 02:16:42,465 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2020-07-31 02:16:42,470 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2020-07-31 02:16:42,471 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2020-07-31 02:16:42,475 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2020-07-31 02:16:42,499 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on raspberrypi for SSDP
2020-07-31 02:16:42,529 - octoprint.server - INFO - Listening on http://0.0.0.0:5000 and http://[::]:5000
2020-07-31 02:16:42,554 - octoprint.plugins.announcements - INFO - Looks like we are offline, can't fetch announcements for channel _important from network
2020-07-31 02:16:42,577 - octoprint.plugins.announcements - INFO - Looks like we are offline, can't fetch announcements for channel _releases from network
2020-07-31 02:16:42,584 - octoprint.plugins.announcements - INFO - Looks like we are offline, can't fetch announcements for channel _blog from network
2020-07-31 02:16:42,637 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2020-07-31 02:16:42,787 - octoprint.plugins.announcements - INFO - Looks like we are offline, can't fetch announcements for channel _plugins from network
2020-07-31 02:16:43,141 - octoprint.plugins.announcements - INFO - Looks like we are offline, can't fetch announcements for channel _octopi from network
2020-07-31 02:16:43,779 - octoprint.util.pip - INFO - Using "/home/pi/OctoPrint/venv/bin/python2 -m pip" as command to invoke pip
2020-07-31 02:16:43,781 - octoprint.util.pip - INFO - pip installs to /home/pi/OctoPrint/venv/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-07-31 02:16:43,781 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-07-31 02:16:44,256 - octoprint.plugins.pluginmanager - INFO - Looks like we are offline, can't fetch notices from network
2020-07-31 02:16:44,277 - octoprint.plugins.detailedprogress - INFO - OctoPrint-DetailedProgress loaded!
2020-07-31 02:16:44,431 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.0.100:5000/'}
2020-07-31 02:16:54,328 - octoprint.server.preemptive_cache - INFO - ... done in 9.90s
^C2020-07-31 02:17:11,948 - octoprint.server - INFO - Shutting down...
2020-07-31 02:17:12,583 - octoprint.events - INFO - Processing shutdown event, this will be our last event
2020-07-31 02:17:12,587 - octoprint.events - INFO - Event loop shut down
2020-07-31 02:17:12,628 - octoprint.server - INFO - Goodbye!

```

**Comment by foosel** [comment]
As already said, that is a problem with a plugin, not OctoPrint. You need to take this up with the plugin author.
