### ISSUE TITLE
ModuleNotFoundError: No Module named 'apscheduler'

### ISSUE THREAD

**Issue by zhaojunqin93** [OctoPrint/OctoPrint#4052]
### The problem

When I install a plugin, there is an error "ModuleNotFoundError: No Module named 'apscheduler'". I tried to install the plugin via Octoprint's Plugin Manager and manual method, but neither worked and the same error was shown. Plus, I tried to install APScheduler in different location, such as the base, in raspberry pi. But None of them worked, and same error.

### Did the issue persist even in safe mode?

No, it did not persist (it's an issue with one of your installed plugins, don't report here)

### Version of OctoPrint

1.5.2

### Operating system running OctoPrint

Linux

### Checklist of files to include below

- [X] octoprint.log
- [ ] serial.log or contents of your terminal tab (always include in cases of issues with printer communication)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

2021-03-16 02:49:12,267 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2021-03-16 02:53:02,811 - octoprint.plugin.core - ERROR - Error loading plugin CMfgDataAcquisition
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 1298, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 69, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_CMfgDataAcquisition/__init__.py", line 13, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ModuleNotFoundError: No module named 'apscheduler'
2021-03-16 02:53:02,819 - octoprint.plugins.pluginmanager - WARNING - The plugin was installed successfully,

**Comment by foosel** [comment]
The issue didn't persist in safe mode, so it's an issue with one of your third party plugins and not OctoPrint.

Your error points at octoprint_CMfgDataAcquisition.
