### ISSUE TITLE
Missing Tabs

### ISSUE THREAD

**Issue by RWoerz** [OctoPrint/OctoPrint#4257]
Tried updating to 1.7.0 and lost the temperature tab and maybe others. All I have is gcode viewer, terminal and timelapse tabs. I also get this error when I try to connect to my printer. I've uninstalled all plugins. I have a CNC router and loaded the Better GRBL plugin to see what that was about but have since uninstalled it. It's worked great for a long time. I have an Ultimaker Original + printer and it's the only one listed.

| Printer requested line 1 but no sufficient history is available, can't resend
2021-10-12 18:28:40,954 - octoprint.util.comm - INFO - Changing monitoring state from "Connecting" to "Operational"
2021-10-12 18:28:51,319 - octoprint.printer.standard.job - INFO - Print job selected - origin: local, path: UMO_printhead_Rear.gcode, owner: rwoerz, user: rwoerz
2021-10-12 18:29:13,061 - octoprint.util.comm - INFO - Communication timeout during an active resend, resending same line again to trigger response from printer.
2021-10-12 18:29:13,065 - octoprint.util.comm - ERROR - Something crashed inside the serial connection loop, please report this in OctoPrint's bug tracker:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 2465, in _monitor
    self._handle_timeout()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 3145, in _handle_timeout
    if self._resendSameCommand():
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 4140, in _resendSameCommand
    return self._resendNextCommand(again=True)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 4163, in _resendNextCommand
    cmd = self._lastLines[-self._resendDelta].decode("ascii")
IndexError: deque index out of range
2021-10-12 18:29:13,098 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Offline after error"
2021-10-12 18:29:13,110 - octoprint.plugins.action_command_notification - INFO - Notifications cleared

**Comment by jneilliii** [comment]
updated path on that nano command, should have been `nano ~/.octoprint/config.yam`

**Comment by jneilliii** [comment]
updated path on that nano command, should have been `nano ~/.octoprint/config.yaml`
