### ISSUE TITLE
Upgrading 1.6.1 to 1.7 - assertion error

### ISSUE THREAD

**Issue by dirknerkle** [OctoPrint/OctoPrint#4262]
### The problem

The OctoPi update is not successful. The log indicates:

2021-10-16 02:14:00,468 > Downloading https://files.pythonhosted.org/packages/96/0a/67556e9b7782df7118c1f49bdc494da5e5e429c93aa77965f33e81287c8c/zipp-1.2.0-py2.py3-none-any.whl
2021-10-16 02:14:01,239 ! Exception:
2021-10-16 02:14:01,240 ! Traceback (most recent call last):
2021-10-16 02:14:01,242 ! File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
2021-10-16 02:14:01,243 ! status = self.run(options, args)
2021-10-16 02:14:01,244 ! File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 346, in run
2021-10-16 02:14:01,244 ! session=session, autobuilding=True
2021-10-16 02:14:01,245 ! File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_internal/wheel.py", line 886, in build
2021-10-16 02:14:01,245 ! assert have_directory_for_build
2021-10-16 02:14:01,246 ! AssertionError

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

Irrelevant. Am not printing - am trying to update the software

### Version of OctoPrint

1.6.1

### Operating system running OctoPrint

OctoPi

### Printer model & used firmware incl. version

irrelevant

### Browser and version of browser, operating system running browser

Chrome 94.0.4606.81

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

Version 1.6.1 works fine. When I start it up, I'm given the option to upgrade it since there is a newer version available. I click the upgrade button, it goes through the motions but eventually, the upgrade is unsuccessful because of an "assertion error."

**Comment by foosel** [comment]
Literally pinned to thus very issue tracker.

https://community.octoprint.org/t/trying-to-update-octoprint-on-octopi-0-16-gives-me-an-assertionerror-about-assert-have-directory-for-build-how-do-i-solve-this/13282
