### ISSUE TITLE
Printer randomly disconnects from Octoprint 

### ISSUE THREAD

**Issue by toophast2catch** [OctoPrint/OctoPrint#4284]
### The problem

Printer is an Ender 3 Pro running an SKR Mini E3 v2.0. Marlin version is 2.0.6.1. Printer will randomly disconnect from Octoprint after being idol for about an hour. I see this in the octoprint log: 

2021-10-27 09:49:06,837 - octoprint.util.comm - ERROR - Could not set low latency mode on serial port, continuing without
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/serial/serialposix.py", line 144, in set_low_latency_mode
    fcntl.ioctl(self.fd, termios.TIOCSSERIAL, buf)
OSError: [Errno 95] Operation not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 3758, in default
    serial_obj.set_low_latency_mode(True)
  File "/home/pi/oprint/lib/python3.7/site-packages/serial/serialposix.py", line 146, in set_low_latency_mode
    raise ValueError('Failed to update ASYNC_LOW_LATENCY flag to {}: {}'.format(low_latency_settings, e))
ValueError: Failed to update ASYNC_LOW_LATENCY flag to True: [Errno 95] Operation not supported
2021-10-27 09:49:06,837 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s

The only way I can get the printer to recconect is by turning it off/back on. 

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### Version of OctoPrint

1.7.0

### Operating system running OctoPrint

Windows 10

### Printer model & used firmware incl. version

stated above

### Browser and version of browser, operating system running browser

Google Chrome

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [X] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[Octoprint.zip](https://github.com/OctoPrint/OctoPrint/files/7428737/Octoprint.zip)

**Comment by foosel** [comment]
Probably fixed by disabling latency mode by default again in 1.7.1
