### ISSUE TITLE
Creating a backup more than once per second fails on windows

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint#4347]
### The problem

Backups are named with a timestamp, down to the second. When the backup API is called twice (or more) in the same second, the backups get the same name. On windows (at least, haven't checked others) this means it fails because the file is already in use.

```
2021-12-18 18:56:30,366 - tornado.access - INFO - 201 POST /plugin/backup/backup (::1) 55.53ms
2021-12-18 18:56:30,367 - tornado.access - INFO - 200 POST /plugin/backup/backup (::1) 56.52ms
2021-12-18 18:56:30,391 - octoprint.plugins.backup - INFO - Creating backup zip at C:\Users\charl.TERRANCE\AppData\Roaming\OctoPrint\data\backup\.Development-one-backup-20211218-185630.zip (excluded: timelapse,timelapse_tmp)...
2021-12-18 18:56:30,694 - tornado.access - INFO - 201 POST /plugin/backup/backup (::1) 48.67ms
2021-12-18 18:56:30,694 - tornado.access - INFO - 200 POST /plugin/backup/backup (::1) 48.67ms
2021-12-18 18:56:30,740 - octoprint.plugins.backup - INFO - Creating backup zip at C:\Users\charl.TERRANCE\AppData\Roaming\OctoPrint\data\backup\.Development-one-backup-20211218-185630.zip (excluded: -)...
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\charl.TERRANCE\\AppData\\Roaming\\OctoPrint\\data\\backup\\.Development-one-backup-20211218-185630.zip' -> 'C:\\Users\\charl.TERRANCE\\AppData\\Roaming\\OctoPrint\\data\\backup\\Development-one-backup-20211218-185630.zip'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 910, in run
2021-12-18 18:56:57,382 - octoprint.plugins.backup - ERROR - Error while creating backup zip
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\charl.TERRANCE\\AppData\\Roaming\\OctoPrint\\data\\backup\\.Development-one-backup-20211218-185630.zip' -> 'C:\\Users\\charl.TERRANCE\\AppData\\Roaming\\OctoPrint\\data\\backup\\Development-one-backup-20211218-185630.zip'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\charl.TERRANCE\Development\OctoPrint Core\OctoPrint\src\octoprint\plugins\backup\__init__.py", line 1087, in _create_backup
    shutil.move(temporary_path, final_path)
  File "C:\Program Files\Python39\lib\shutil.py", line 827, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\charl.TERRANCE\\AppData\\Roaming\\OctoPrint\\data\\backup\\.Development-one-backup-20211218-185630.zip'
2021-12-18 18:56:57,447 - tornado.access - INFO - 200 GET /plugin/backup/ (::1) 51.26ms
    self._target(*self._args, **self._kwargs)
  File "C:\Users\charl.TERRANCE\Development\OctoPrint Core\OctoPrint\src\octoprint\plugins\backup\__init__.py", line 1087, in _create_backup
    shutil.move(temporary_path, final_path)
  File "C:\Program Files\Python39\lib\shutil.py", line 827, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\charl.TERRANCE\\AppData\\Roaming\\OctoPrint\\data\\backup\\.Development-one-backup-20211218-185630.zip'
python-BaseException
Exception in thread Thread-42:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\charl.TERRANCE\\AppData\\Roaming\\OctoPrint\\data\\backup\\.Development-one-backup-20211218-185630.zip' -> 'C:\\Users\\charl.TERRANCE\\AppData\\Roaming\\OctoPrint\\data\\backup\\Development-one-backup-20211218-185630.zip'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\charl.TERRANCE\Development\OctoPrint Core\OctoPrint\src\octoprint\plugins\backup\__init__.py", line 1087, in _create_backup
    shutil.move(temporary_path, final_path)
  File "C:\Program Files\Python39\lib\shutil.py", line 827, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\charl.TERRANCE\\AppData\\Roaming\\OctoPrint\\data\\backup\\.Development-one-backup-20211218-185630.zip'
```

Rather than trying to make a unique name, we could just block more than one backup from taking place at any one time, returning an error?

I might put in a PR for this, but don't count on it as I've had a lot of stuff to do recently. Also, don't ask why I'm creating so many backups :)

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

PR #4322

### Operating system running OctoPrint

Windows 11

### Printer model & used firmware incl. version

VIRTUAL

### Browser and version of browser, operating system running browser

Edge 96

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

I'm not going to include the log file as I've been trying to work out issues automatically uploading the backups to OneDrive, which has involved logging entire requests/responses from Microsoft graph for the last day. Massive pain but I don't really want to risk any secrets being exposed...

**Comment by jneilliii** [comment]
don't do that...:smile:
