### ISSUE TITLE
Unable to install any plugins

### ISSUE THREAD

**Issue by DylanBarber** [OctoPrint/OctoPrint#4351]
### The problem

Fresh install of Octopi (Latest) on a brand new Rpi Zero W 2.
Whenever attempting to install a plugin I get the following:
`Unexpected error while trying to install plugin from None`

Full error below and octoprint.log attached

`2021-12-23 01:20:45,468 - octoprint.plugins.pluginmanager - ERROR - Unexpected error while trying to install plugin from None
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/
[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/7766092/octoprint.log)
pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x6c356cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix/archive/master.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x6c356cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 761, in command_install
    path = download_file(url, folder.name)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/net.py", line 253, in download_file
    with requests.get(url, stream=True) as r:
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix/archive/master.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x6c356cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
`

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.7.2

### Operating system running OctoPrint

OctoPi

### Browser and version of browser, operating system running browser

Google Chrome 96.0.4664.110 - Windows 10 64 bit 10.0.19044 Build 19044

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/7766654/octoprint.log)
[octoprint-systeminfo-20211223022114.zip](https://github.com/OctoPrint/OctoPrint/files/7766656/octoprint-systeminfo-20211223022114.zip)

-No errors show in JS console when this error occurs

**Comment by DylanBarber** [comment]
Closing this issue as I've fixed it. For anyone else that experiences this, check your dns config in `/etc/dhcpcd.conf` and make sure there either isn't any custom dns config at the bottom or that your DNS server configuration IP is correct
