### ISSUE TITLE
Print freeze due to thread not starting or serial connection loop issue

### ISSUE THREAD

**Issue by gitnickgit** [OctoPrint/OctoPrint#4414]
So the below error is happening which causes the printer to stop printing.  I have to cancel the print manually and restart the EZPI server.  The error below is at the end of the attached log file.  If I need to do additional logging I can turn on whatever to get what you need as I can repro the error. 

The new  thread not starting might be a red herring or potential running out of file descriptors?  as the camera capture plugin seems to keep trying to capture after it fails initial try.  try/except should maybe be done here to prevent retrying

RuntimeError: can't start new thread
2022-02-10 17:39:17,353 - octoprint.util.comm - INFO - Got a resend request from the printer: requested line = 98559, current line = 98560
| Last lines in terminal:
| Send: N98551 G1 X108.134 Y80.697 E1332.26575*109
| Recv: ok N98551 P2 B3
| Send: N98552 G1 X108.11 Y80.99 E1332.27481*107
| Recv: ok N98552 P2 B3
| Send: N98553 G1 X108.067 Y81.242 E1332.28269*97
| Recv: ok N98553 P2 B3
| Send: N98554 G1 X107.99 Y81.525 E1332.29172*86
| Recv: ok N98554 P2 B3
| Send: N98555 G1 X107.879 Y81.819 E1332.3014*90
| Recv: ok N98555 P2 B3
| Send: N98556 G1 X107.749 Y82.077 E1332.3103*81
| Recv: ok N98556 P2 B3
| Send: N98557 G1 X107.601 Y82.316 E1332.31896*109
| Recv: ok N98557 P2 B3
| Send: N98558 G1 X107.441 Y82.527 E1332.32712*96
| Recv: ok N98558 P2 B3
| Send: N98559 G1 X107.248 Y82.738 E1332.33593*104
| Recv:  T:214.84 /215.00 B:60.74 /60.00 @:77 B@:0
| Recv: Error:Line Number is not Last Line Number+1, Last Line: 98558
| Recv: Resend: 98559
2022-02-10 17:39:17,356 - octoprint.util.comm - ERROR - Something crashed inside the serial connection loop, please report this in OctoPrint's bug tracker:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 2477, in _monitor
    self._handle_resend_request(line)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 4189, in _handle_resend_request
    self._resend_ok_timer.start()
  File "/usr/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
2022-02-10 17:39:17,379 - oct
[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/8043439/octoprint.log)
oprint.util.comm - INFO - Changing monitoring state from "Printing" to "Offline after error"
2022-02-10 17:39:17,396 - octoprint.plugins.action_command_notification - INFO - Notifications cleare
[octoprint-systeminfo-20220210184130.zip](https://github.com/OctoPrint/OctoPrint/files/8043526/octoprint-systeminfo-20220210184130.zip)
d

**Comment by foosel** [comment]
Did you open the bug report on mobile by any chance?
