### ISSUE TITLE
[1.8.0dev] 500 error on `/api/printer` endpoint

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint#4439]
### The problem

1. Started a print with the virtual printer
2. Tried to request the `/api/printer` endpoint for the printer state
3. Got a 500 internal server error:

```py
2022-02-26 18:09:44,636 - octoprint - ERROR - Exception on /api/printer [GET]
Traceback (most recent call last):
  File "C:\Users\charl\Development\venv310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\charl\Development\venv310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\charl\Development\venv310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\charl\Development\venv310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\charl\development\octoprint core\octoprint\src\octoprint\vendor\flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "c:\users\charl\development\octoprint core\octoprint\src\octoprint\server\api\printer.py", line 51, in printerState
    result.update({"temperature": _get_temperature_data(processor)})
  File "c:\users\charl\development\octoprint core\octoprint\src\octoprint\server\api\printer.py", line 463, in _get_temperature_data
    tempData = printer.get_current_temperatures()
  File "c:\users\charl\development\octoprint core\octoprint\src\octoprint\printer\standard.py", line 840, in get_current_temperatures
    return {
  File "c:\users\charl\development\octoprint core\octoprint\src\octoprint\printer\standard.py", line 842, in <dictcomp>
    "actual": value["actual"],
TypeError: 'int' object is not subscriptable
2022-02-26 18:09:44,638 - tornado.access - ERROR - 500 GET /api/printer (::1) 3.84ms
```

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

 OctoPrint 1.8.0.dev309+gfa609eb23

### Operating system running OctoPrint

Windows 11

### Printer model & used firmware incl. version

VIRTUAL

### Browser and version of browser, operating system running browser

Edge 98.0.1108.62

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220226181338.zip](https://github.com/OctoPrint/OctoPrint/files/8147184/octoprint-systeminfo-20220226181338.zip)

**Comment by cp2004** [comment]
I think it was probably https://github.com/OctoPrint/OctoPrint/commit/939d9585b4355f897cfd4eb8dea6ff10bc9442f4 that broke it, but I haven't been able to confirm yet.
