### ISSUE TITLE
Backup fails to restore

### ISSUE THREAD

**Issue by jagauthier** [OctoPrint/OctoPrint#4446]
### The problem

Backed up octoprint config (1.7.3) on one machine and tried to restore it on another with the same version.
[octoprint-systeminfo-20220306015300.zip](https://github.com/OctoPrint/OctoPrint/files/8191813/octoprint-systeminfo-20220306015300.zip)

```
2022-03-06 01:48:14,548 - octoprint.plugins.backup - ERROR - Error while running restore
Traceback (most recent call last):
  File "/home/user/octoprint/lib/python3.9/site-packages/octoprint/plugins/backup/__init__.py", line 1260, in _restore_backup
    on_install_plugins(known_plugins)
  File "/home/user/octoprint/lib/python3.9/site-packages/octoprint/plugins/backup/__init__.py", line 292, in on_install_plugins
    self.__class__._install_plugin(
  File "/home/user/octoprint/lib/python3.9/site-packages/octoprint/plugins/backup/__init__.py", line 914, in _install_plugin
    cls._pip_caller.execute(*pip)
  File "/home/user/octoprint/lib/python3.9/site-packages/octoprint/util/pip.py", line 208, in execute
    return self.call(command, **kwargs)
  File "/home/user/octoprint/lib/python3.9/site-packages/octoprint/util/commandline.py", line 244, in call
    all_stdout += process_stdout(p.stdout.readlines(timeout=0.5))
  File "/home/user/octoprint/lib/python3.9/site-packages/octoprint/util/commandline.py", line 236, in process_stdout
    return process_lines(lines, self._log_stdout)
  File "/home/user/octoprint/lib/python3.9/site-packages/octoprint/util/commandline.py", line 229, in process_lines
    processed = self._preprocess_lines(
  File "/home/user/octoprint/lib/python3.9/site-packages/octoprint/util/pip.py", line 498, in _preprocess_lines
    return list(map(self._preprocess, lines))
  File "/home/user/octoprint/lib/python3.9/site-packages/octoprint/util/pip.py", line 517, in _preprocess
    return to_unicode(clean_ansi(text))
  File "/home/user/octoprint/lib/python3.9/site-packages/octoprint/util/commandline.py", line 57, in clean_ansi
    return _ANSI_REGEX.sub(b"", line.encode("latin1")).decode("latin1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-44: ordinal not in range(256)
2022-03-06 01:48:14,554 - octoprint.plugins.backup - INFO - Removing temporary zip

```

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

I didn't try this in safe mode because there aren't any plugins actually installed at this time.

### Version of OctoPrint

1.7.3

### Operating system running OctoPrint

Debian

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220306015300.zip](https://github.com/OctoPrint/OctoPrint/files/8191815/octoprint-systeminfo-20220306015300.zip)

**Comment by cp2004** [comment]
See #4392
