### ISSUE TITLE
[1.8.0rc1] Crash in serial loop on garbage/weird custom entry in temperature line

### ISSUE THREAD

**Issue by foosel** [OctoPrint/OctoPrint#4456]
### Problem

Line:

```
Recv:  T:210.04 /210.00 B:52.00 /52.00 @:85 B@:31pS_XYZ:5
```

leads to

```
2022-03-15 07:44:15,511 - octoprint.util.comm - ERROR - Something crashed inside the serial connection loop, please report this in OctoPrint's bug tracker:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 2642, in _monitor
    self._processTemperatures(line)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 2165, in _processTemperatures
    self.last_temperature.set_custom(key, actual=actual, target=target)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 370, in set_custom
    raise ValueError(f"{identifier} is a reserved identifier")
ValueError: 31pS_XYZ is a reserved identifier
2022-03-15 07:44:15,703 - octoprint.util.comm - INFO - Changing monitoring state from "Printing" to "Offline after error"
```

The validation regex is too broad (and actually shouldn't be needed in any case), and the `ValueError` never gets caught and handled either.

### Solution

Remove or unbroaden regex, add some more test cases for this stuff, make sure no parsing errors on custom values for the temperatures can lead to full serial loop crashs.

**Comment by foosel** [comment]
1.8.0rc2 has been released.
