### ISSUE TITLE
update 1.8.0rc2 failed

### ISSUE THREAD

**Issue by Reperiel** [OctoPrint/OctoPrint#4462]
### The problem

I have tried to update from 1.7.3 to 1.8.0rc2. It produced a popup claiming the update failed.

plugin_softwareupdate_console.log
`2022-03-16 13:17:15,948   /home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install https://github.com/OctoPrint/OctoPrint/archive/1.8.0rc2.zip --no-cache-dir
2022-03-16 13:17:18,464 > Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2022-03-16 13:17:18,465 > Collecting https://github.com/OctoPrint/OctoPrint/archive/1.8.0rc2.zip
2022-03-16 13:17:18,465 > Downloading https://github.com/OctoPrint/OctoPrint/archive/1.8.0rc2.zip (6.6 MB)
`
octoprint.log
`2022-03-16 13:17:15,938 - octoprint.plugins.softwareupdate - INFO - Starting update of octoprint to 1.8.0rc
2...
2022-03-16 13:17:40,869 - octoprint.plugins.softwareupdate - ERROR - Update of octoprint can not be perform
ed, please also check plugin_softwareupdate_console.log for possible causes of this
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 209
0, in _perform_update
    else:
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line
 115, in perform_update
    _log_message(
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/pip.py", line 208, in execute
    CommandlineCaller.__init__(self)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 244, in call
    # thread
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 236, in process_st
dout
    }
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 230, in process_li
nes
    kwargs.update(
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/pip.py", line 498, in _preprocess_lines
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/pip.py", line 517, in _preprocess
    # This is horribly ugly and I'm sorry...
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 57, in clean_ansi
    return to_bytes(_ANSI_REGEX.sub("", to_unicode(line)))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-44: ordinal not in range(256)
2022-03-16 13:17:40,915 - octoprint.plugins.softwareupdate - INFO - Saved update log to disk
2022-03-16 13:17:41,011 - octoprint.plugins.tracking - INFO - Sent tracking event update_failed, payload: {
'target': 'octoprint', 'from_version': '1.7.3', 'to_version': '1.8.0rc2'}
`
Creating a system-bundle gives: 500: Internal Server Error

After a reboot the version is 1.8.0 and the system-bundle works.
[octoprint-systeminfo-20220316133039.zip](https://github.com/OctoPrint/OctoPrint/files/8262105/octoprint-systeminfo-20220316133039.zip)

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

The update had kind of worked even if there was an error message so I can't update in safe mode again.

### Version of OctoPrint

1.7.3

### Operating system running OctoPrint

OctoPi 1.8.0

### Browser and version of browser, operating system running browser

firefox 98.0, opensuse tumbleweed

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by cp2004** [comment]
The issue has been fixed in OctoPrint 1.8.0, it's an incompatibility with pip 22.

https://community.octoprint.org/t/i-cannot-install-uninstall-update-plugins-update-octoprint-or-restore-a-backup-i-get-a-unicodeencodeerror-latin-1-codec-cant-encode-characters/42684

**Comment by foosel** [comment]
I was just about to say the same ^^
