### ISSUE TITLE
Octoprint 1.9.0rc2 does not start on Debian 12

### ISSUE THREAD

**Issue by guillaume-pais** [OctoPrint/OctoPrint#4765]
### The problem

We tried Octoprint 1.9.0rc2 and it does not seem to run on Debian 12:

```
guillaume@debian:~$ cd /tmp/
guillaume@debian:/tmp$ mkdir octo
guillaume@debian:/tmp$ cd octo/
git clone https://github.com/OctoPrint/OctoPrint.git
Cloning into 'OctoPrint'...
remote: Enumerating objects: 85567, done.
remote: Counting objects: 100% (584/584), done.
remote: Compressing objects: 100% (350/350), done.
remote: Total 85567 (delta 264), reused 502 (delta 223), pack-reused 84983
Receiving objects: 100% (85567/85567), 51.33 MiB | 13.47 MiB/s, done.
Resolving deltas: 100% (55873/55873), done.
guillaume@debian:/tmp/octo$ cd OctoPrint/
guillaume@debian:/tmp/octo/OctoPrint$ git checkout 1.9.0rc2
Note: switching to '1.9.0rc2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 95e87eb19 ⏪ Bring back `octoprint_setuptools`
guillaume@debian:/tmp/octo/OctoPrint$ cd ..
guillaume@debian:/tmp/octo$ virtualenv --python=python3 venv
created virtual environment CPython3.11.2.final.0-64 in 207ms
  creator CPython3Posix(dest=/tmp/octo/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/guillaume/.local/share/virtualenv)
    added seed packages: pip==23.0.1, setuptools==66.1.1, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
guillaume@debian:/tmp/octo$ . venv/bin/activate
(venv) guillaume@debian:/tmp/octo$ pip3 install ./OctoPrint/
Processing ./OctoPrint
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting OctoPrint-FileCheck>=2021.2.23
  Using cached OctoPrint_FileCheck-2021.2.23-py2.py3-none-any.whl (19 kB)
Collecting OctoPrint-FirmwareCheck>=2021.10.11
  Using cached OctoPrint_FirmwareCheck-2021.10.11-py2.py3-none-any.whl (33 kB)
Collecting OctoPrint-PiSupport>=2022.6.13
  Using cached OctoPrint_PiSupport-2022.6.13-py2.py3-none-any.whl (33 kB)
Collecting argon2-cffi<22,>=21.3.0
  Using cached argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting Babel<2.13,>=2.12.1
  Using cached Babel-2.12.1-py3-none-any.whl (10.1 MB)
Collecting cachelib<0.11,>=0.10.2
  Using cached cachelib-0.10.2-py3-none-any.whl (18 kB)
Collecting Click<9,>=8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting colorlog<7,>=6.7.0
  Using cached colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Collecting emoji<3,>=2.2.0
  Using cached emoji-2.2.0-py3-none-any.whl
Collecting feedparser<7,>=6.0.10
  Using cached feedparser-6.0.10-py3-none-any.whl (81 kB)
Collecting filetype<2,>=1.2.0
  Using cached filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Collecting Flask-Assets<3,>=2.0
  Using cached Flask_Assets-2.0-py3-none-any.whl (8.5 kB)
Collecting Flask-Babel<4,>=3.0.1
  Using cached flask_babel-3.0.1-py3-none-any.whl (11 kB)
Collecting Flask-Login<0.7,>=0.6.2
  Using cached Flask_Login-0.6.2-py3-none-any.whl (17 kB)
Collecting Flask-Limiter<4,>=3.3.0
  Using cached Flask_Limiter-3.3.0-py3-none-any.whl (27 kB)
Collecting flask<2.3,>=2.2.3
  Using cached Flask-2.2.3-py3-none-any.whl (101 kB)
Collecting frozendict<3,>=2.3.5
  Using cached frozendict-2.3.5-cp311-cp311-linux_x86_64.whl
Collecting future<1,>=0.18.3
  Using cached future-0.18.3-py3-none-any.whl
Collecting markdown<4,>=3.4.1
  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
Collecting netaddr<0.9,>=0.8
  Using cached netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
Collecting netifaces<1,>=0.11
  Using cached netifaces-0.11.0-cp311-cp311-linux_x86_64.whl
Collecting passlib<2,>=1.7.4
  Using cached passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Collecting pathvalidate<3,>=2.5.2
  Using cached pathvalidate-2.5.2-py3-none-any.whl (20 kB)
Collecting pkginfo<2,>=1.9.6
  Using cached pkginfo-1.9.6-py3-none-any.whl (30 kB)
Collecting psutil<6,>=5.9.4
  Using cached psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
Collecting pydantic<2,>=1.10.5
  Using cached pydantic-1.10.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting pylru<2,>=1.2.1
  Using cached pylru-1.2.1-py3-none-any.whl (16 kB)
Collecting pyserial<4,>=3.5
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting PyYAML<6,>=5.4.1
  Using cached PyYAML-5.4.1-cp311-cp311-linux_x86_64.whl
Collecting requests<3,>=2.28.2
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting sarge==0.1.7.post1
  Using cached sarge-0.1.7.post1-py2.py3-none-any.whl (18 kB)
Collecting semantic-version<3,>=2.10.0
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting sentry-sdk<2,>=1.16.0
  Using cached sentry_sdk-1.16.0-py2.py3-none-any.whl (184 kB)
Collecting tornado<7,>=6.2
  Using cached tornado-6.2-cp37-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (423 kB)
Collecting watchdog<3,>=2.3.1
  Using cached watchdog-2.3.1-py3-none-manylinux2014_x86_64.whl (80 kB)
Collecting websocket-client<2,>=1.5.1
  Using cached websocket_client-1.5.1-py3-none-any.whl (55 kB)
Collecting werkzeug<2.3,>=2.2.3
  Using cached Werkzeug-2.2.3-py3-none-any.whl (233 kB)
Collecting wrapt<1.16,>=1.15
  Using cached wrapt-1.15.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (78 kB)
Collecting zeroconf==0.39.4
  Using cached zeroconf-0.39.4-py3-none-any.whl (106 kB)
Collecting zipstream-ng<2.0.0,>=1.4.0
  Using cached zipstream_ng-1.4.0-py3-none-any.whl (21 kB)
Collecting blinker<2,>=1.5
  Using cached blinker-1.5-py2.py3-none-any.whl (12 kB)
Collecting class-doc<0.3,>=0.2.6
  Using cached class_doc-0.2.6-py3-none-any.whl (4.7 kB)
Collecting regex
  Using cached regex-2022.10.31-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
Collecting unidecode
  Using cached Unidecode-1.3.6-py3-none-any.whl (235 kB)
Requirement already satisfied: wheel in ./venv/lib/python3.11/site-packages (from OctoPrint==1.9.0rc2) (0.38.4)
Collecting async-timeout>=4.0.1
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting ifaddr>=0.1.7
  Using cached ifaddr-0.2.0-py3-none-any.whl (12 kB)
Collecting argon2-cffi-bindings
  Using cached argon2_cffi_bindings-21.2.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (86 kB)
Collecting more-itertools>=5.0.0
  Using cached more_itertools-9.1.0-py3-none-any.whl (54 kB)
Collecting sgmllib3k
  Using cached sgmllib3k-1.0.0-py3-none-any.whl
Collecting Jinja2>=3.0
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting itsdangerous>=2.0
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting webassets>=2.0
  Using cached webassets-2.0-py3-none-any.whl (142 kB)
Collecting pytz<2023.0,>=2022.7
  Using cached pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
Collecting limits>=2.8
  Using cached limits-3.2.0-py3-none-any.whl (43 kB)
Collecting ordered-set<5,>4
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting rich<14,>=12
  Using cached rich-13.3.2-py3-none-any.whl (238 kB)
Collecting typing-extensions>=4
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (197 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting MarkupSafe>=2.1.1
  Using cached MarkupSafe-2.1.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27 kB)
Collecting deprecated>=1.2
  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: setuptools in ./venv/lib/python3.11/site-packages (from limits>=2.8->Flask-Limiter<4,>=3.3.0->OctoPrint==1.9.0rc2) (66.1.1)
Collecting packaging<24,>=21
  Using cached packaging-23.0-py3-none-any.whl (42 kB)
Collecting markdown-it-py<3.0.0,>=2.2.0
  Using cached markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
Collecting pygments<3.0.0,>=2.13.0
  Using cached Pygments-2.14.0-py3-none-any.whl (1.1 MB)
Collecting cffi>=1.0.1
  Using cached cffi-1.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (462 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Building wheels for collected packages: OctoPrint
  Building wheel for OctoPrint (pyproject.toml) ... done
  Created wheel for OctoPrint: filename=OctoPrint-1.9.0rc2-py2.py3-none-any.whl size=3285914 sha256=f1641931d6a4bba6637136610b5b75669f938781c0aa0a74ff77542851348789
  Stored in directory: /tmp/pip-ephem-wheel-cache-5s88ofrz/wheels/2f/f2/fd/5a849ab2198317dc56aa0e1c0d5b12fd5f766a7700247ace03
Successfully built OctoPrint
Installing collected packages: webassets, sgmllib3k, sarge, pytz, pyserial, pylru, passlib, OctoPrint-PiSupport, OctoPrint-FirmwareCheck, OctoPrint-FileCheck, netifaces, netaddr, ifaddr, filetype, zipstream-ng, wrapt, websocket-client, watchdog, urllib3, unidecode, typing-extensions, tornado, semantic-version, regex, PyYAML, pygments, pycparser, psutil, pkginfo, pathvalidate, packaging, ordered-set, more-itertools, mdurl, MarkupSafe, markdown, itsdangerous, idna, future, frozendict, feedparser, emoji, colorlog, Click, charset-normalizer, certifi, cachelib, blinker, Babel, async-timeout, zeroconf, werkzeug, sentry-sdk, requests, pydantic, markdown-it-py, Jinja2, deprecated, class-doc, cffi, rich, limits, flask, argon2-cffi-bindings, Flask-Login, Flask-Limiter, Flask-Babel, Flask-Assets, argon2-cffi, OctoPrint
Successfully installed Babel-2.12.1 Click-8.1.3 Flask-Assets-2.0 Flask-Babel-3.0.1 Flask-Limiter-3.3.0 Flask-Login-0.6.2 Jinja2-3.1.2 MarkupSafe-2.1.2 OctoPrint-1.9.0rc2 OctoPrint-FileCheck-2021.2.23 OctoPrint-FirmwareCheck-2021.10.11 OctoPrint-PiSupport-2022.6.13 PyYAML-5.4.1 argon2-cffi-21.3.0 argon2-cffi-bindings-21.2.0 async-timeout-4.0.2 blinker-1.5 cachelib-0.10.2 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-3.1.0 class-doc-0.2.6 colorlog-6.7.0 deprecated-1.2.13 emoji-2.2.0 feedparser-6.0.10 filetype-1.2.0 flask-2.2.3 frozendict-2.3.5 future-0.18.3 idna-3.4 ifaddr-0.2.0 itsdangerous-2.1.2 limits-3.2.0 markdown-3.4.1 markdown-it-py-2.2.0 mdurl-0.1.2 more-itertools-9.1.0 netaddr-0.8.0 netifaces-0.11.0 ordered-set-4.1.0 packaging-23.0 passlib-1.7.4 pathvalidate-2.5.2 pkginfo-1.9.6 psutil-5.9.4 pycparser-2.21 pydantic-1.10.6 pygments-2.14.0 pylru-1.2.1 pyserial-3.5 pytz-2022.7.1 regex-2022.10.31 requests-2.28.2 rich-13.3.2 sarge-0.1.7.post1 semantic-version-2.10.0 sentry-sdk-1.16.0 sgmllib3k-1.0.0 tornado-6.2 typing-extensions-4.5.0 unidecode-1.3.6 urllib3-1.26.15 watchdog-2.3.1 webassets-2.0 websocket-client-1.5.1 werkzeug-2.2.3 wrapt-1.15.0 zeroconf-0.39.4 zipstream-ng-1.4.0
(venv) guillaume@debian:/tmp/octo$ octoprint serve
2023-03-16 04:55:16,257 - octoprint.startup - INFO - ******************************************************************************
2023-03-16 04:55:16,258 - octoprint.startup - INFO - Starting OctoPrint 1.9.0rc2
2023-03-16 04:55:16,258 - octoprint.startup - INFO - ******************************************************************************
2023-03-16 04:55:16,261 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: online
2023-03-16 04:55:16,261 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 1.1.1.1:53 is working
2023-03-16 04:55:16,261 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is working
2023-03-16 04:55:16,263 - octoprint.plugin.core - INFO - Loading plugins from /tmp/octo/venv/lib/python3.11/site-packages/octoprint/plugins, /home/guillaume/.octoprint/plugins and installed plugin packages...
2023-03-16 04:55:16,659 - octoprint.plugin.core - INFO - Plugin Pi Support Plugin (2022.6.13) did not pass check, not loading.
2023-03-16 04:55:16,672 - octoprint.plugin.core - INFO - Found 18 plugin(s) providing 18 mixin implementations, 34 hook handlers
2023-03-16 04:55:16,684 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2023-03-16 04:55:16,714 - octoprint.cli.server - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/tmp/octo/venv/bin/octoprint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/tmp/octo/venv/lib/python3.11/site-packages/octoprint/__init__.py", line 1008, in main
    octo(args=args, prog_name="octoprint", auto_envvar_prefix="OCTOPRINT")
  File "/tmp/octo/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/octo/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/tmp/octo/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/octo/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/octo/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/octo/venv/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/octo/venv/lib/python3.11/site-packages/octoprint/cli/server.py", line 317, in serve_command
    run_server(
  File "/tmp/octo/venv/lib/python3.11/site-packages/octoprint/cli/server.py", line 163, in run_server
    octoprint_server.run()
  File "/tmp/octo/venv/lib/python3.11/site-packages/octoprint/server/__init__.py", line 400, in run
    self._start_intermediary_server()
  File "/tmp/octo/venv/lib/python3.11/site-packages/octoprint/server/__init__.py", line 2654, in _start_intermediary_server
    self._intermediary_server.server_bind()
  File "/usr/lib/python3.11/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.9.0rc2

### Operating system running OctoPrint

Debian 12

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

We cannot get any bundle. It is empty:
```
(venv) guillaume@debian:/tmp/octo$ octoprint systeminfo
(venv) guillaume@debian:/tmp/octo$ 
(venv) guillaume@debian:/tmp/octo$ octoprint --version
octoprint, version 1.9.0rc2

```
[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/10988940/octoprint.log)

**Comment by guillaume-pais** [comment]
Hi @foosel, 

we cannot get any system info bundle from the command line. We added the ```octoprint.log``` file.

Thanks

**Comment by guillaume-pais** [comment]
Thanks for your answer.

We had a conflict with ```snapd```. After uninstall everything works fine.

**Comment by foosel** [comment]
You could also just have told OctoPrint to use a different port with `--port` or via [`config.yaml`](https://docs.octoprint.org/en/master/configuration/config_yaml.html#server).

**Comment by jneilliii** [comment]
have you tried the octoprint_deploy script?

**Comment by DonCanDo** [comment]
Sure it fails too founding my printer not

Grüße Steven
________________________________
