### ISSUE TITLE
Fatal error initializing the platform: Could not initialize event manager: non-string found in code slot

### ISSUE THREAD

**Issue by EveryOtherUsernameWasAlreadyTaken** [OctoPrint/OctoPrint#5035]
### The problem

After upgrading to 1.10.2, Octoprint does not start any more. The website says I should log in and check the logs.

Logging in via SSH, I get the following message in `~/.octoprint/logs/octoprint.log`:

```none
2024-06-28 14:24:22,640 - octoprint.startup - INFO - ******************************************************************************
2024-06-28 14:24:22,644 - octoprint.startup - INFO - Starting OctoPrint 1.10.2
2024-06-28 14:24:22,652 - octoprint.startup - INFO - ******************************************************************************
2024-06-28 14:24:22,786 - octoprint.startup - CRITICAL - Could not initialize event manager: non-string found in code slot
2024-06-28 14:24:22,787 - octoprint.startup - CRITICAL - There was a fatal error starting up OctoPrint.
```

Rebooting does not help.

### Did the issue persist even in safe mode?

Yes, the problem persist:

```bash
pi@octopi:~ $ ~/oprint/bin/octoprint safemode
Traceback (most recent call last):
  File "/home/pi/oprint/bin/octoprint", line 8, in <module>
    sys.exit(main())
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/__init__.py", line 1008, in main
    octo(args=args, prog_name="octoprint", auto_envvar_prefix="OCTOPRINT")
  File "/home/pi/oprint/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/pi/oprint/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/oprint/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/oprint/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/cli/server.py", line 281, in enable_safemode
    settings.save()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/settings/__init__.py", line 1796, in save
    from octoprint.events import Events, eventManager
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/events.py", line 13, in <module>
    import octoprint.plugin
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugin/__init__.py", line 22, in <module>
    from octoprint.plugin.core import Plugin, PluginInfo, PluginManager  # noqa: F401
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 32, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 918, in get_code
  File "<frozen importlib._bootstrap_external>", line 587, in _compile_bytecode
SystemError: non-string found in code slot
```

### Version of OctoPrint

1.10.2 (there is no corner to look that up if the webserver does not start)

### Operating system running OctoPrint

Linux octopi 6.1.21-v7l+ #1642 SMP Mon Apr  3 17:22:30 BST 2023 armv7l GNU/Linux, version of /etc/octopi_version: 1.0.0

### Printer model & used firmware incl. version

Prusa i3 MK3

### Browser and version of browser, operating system running browser

Firefox 127.0.2

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [X] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

## Systeminfo Bundle

I can't include the Systeminfo bundle, if it's only accessible via the web interface. The web interface does not work.

The recovery page is exactly the same as the normal page. I can't download Systeminfo bundle there either.

I can't generate systeminfo bundle on command line, because octoprint cannot be found

```bash
pi@octopi:~ $ octoprint safemode
-bash: octoprint: command not found
pi@octopi:~ $ sudo !!
sudo octoprint safemode
[sudo] password for pi:
sudo: octoprint: command not found
```

and

```bash
pi@octopi:~ $ ~/oprint/bin/octoprint systeminfo .
Could not initialize event manager: non-string found in code slot
There was a fatal error initializing the platform.
```

## Javascript Console

```
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
```

Note: this is the page that says that the webserver cannot be started. That page does not do much.

## Screenshots

![website](https://github.com/OctoPrint/OctoPrint/assets/5978637/f9a8bea6-beb0-409b-8d25-117b9364e334)

![SSH session](https://github.com/OctoPrint/OctoPrint/assets/5978637/f36ed421-6038-4d8b-abc4-32044636bfa7)

![image](https://github.com/OctoPrint/OctoPrint/assets/5978637/4c867296-6d06-4c46-bad6-35b85866e761)

## GCode

It's not a GCode problem. I can't even start printing.

**Comment by EveryOtherUsernameWasAlreadyTaken** [comment]
Dear Bot, I have explained in detail why it isn't possible for me to upload the requested information. I have tried all three methods explained on the page that deals with that information. Please do not close the issue for this reason. 

If that information is so super important, then please make sure that it can be accessed also in ever so severe cases.

**Comment by MarshMaker3D** [comment]
Just a shot in the dark, but maybe rule out corrupt image and/or SD card?

**Comment by EveryOtherUsernameWasAlreadyTaken** [comment]
I formatted the SD card and reinstalled everything from scratch. Raspberrys and/or SD cards suck. Yet another hour wasted.

**Comment by jneilliii** [comment]
Recommend the backup scheduler plugin and one of the cloud based backup plugins to expedite setting up from scratch.
